# Generated by Django 2.2.6 on 2019-10-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
    ]
